### ISSUE TITLE
TensorFlow model conversion failure

### ISSUE THREAD

**Issue by vidyasiv** [dlstreamer/dlstreamer#285]
Open Model Zoo Model name:` yolo-v2-tiny-tf`
Docker Image: `intel/dlstreamer:2022.1.0-ubuntu20-devel`

##### Commands
```
# Start devel container
docker run -it --rm --privileged --net=host -v /home/vidyasiv/.Xauthority:/home/dlstreamer/.Xauthority -v /tmp/.X11-unix -v /tmp:/tmp -e HTTP_PROXY=http://proxy-dmz.intel.com:911 -e HTTPS_PROXY=http://proxy-dmz.intel.com:912 -e http_proxy=http://proxy-dmz.intel.com:911 -e https_proxy=http://proxy-dmz.intel.com:912 --user root --group-add 109 intel/dlstreamer:2022.1.0-ubuntu20-devel
```
- Model Download/Conversion: Option A (`download_models.sh` script)
```
echo 'yolo-v2-tiny-tf ' | tee -a /opt/intel/dlstreamer/samples/models.lst
/opt/intel/dlstreamer/samples/download_models.sh
```
OR
- Model Download/Conversion: Option B (`omz_downloader`, `omz_converter`)
```
# Download model
omz_downloader --name yolo-v2-tiny-tf -o /tmp/
# Convert model
omz_converter --name yolo-v2-tiny-tf --precisions FP16,FP32 -o /tmp/  -d /tmp/
```
##### Output

```
========== Running pre-convert script for yolo-v2-tiny-tf
Pre-convert command: /usr/bin/python3 -- /usr/local/lib/python3.8/dist-packages/openvino/model_zoo/models/public/yolo-v2-tiny-tf/pre-convert.py -- /tmp/public/yolo-v2-tiny-tf /tmp/public/yolo-v2-tiny-tf

Traceback (most recent call last):
  File "/tmp/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/tools/model_converter/convert.py", line 15, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openvino/model_zoo/models/public/yolo-v2-tiny-tf/pre-convert.py", line 44, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/openvino/model_zoo/models/public/yolo-v2-tiny-tf/pre-convert.py", line 29, in main
    subprocess.run([sys.executable, '--',
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '--', '/tmp/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/tools/model_converter/convert.py', '--', '/tmp/public/yolo-v2-tiny-tf/keras-YOLOv3-model-set/cfg/yolov2-tiny.cfg', '/tmp/public/yolo-v2-tiny-tf/yolov2-tiny.weights', '/tmp/public/yolo-v2-tiny-tf/yolo-v2-tiny.h5']' returned non-zero exit status 1.

FAILED:
yolo-v2-tiny-tf
```

##### Workaround

Setting environment variable `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`

**Comment by akwrobel** [comment]
This is no longer a supported model.  Closing.
