### ISSUE TITLE
Failed with /opt/intel/dlstreamer/samples/download_models.sh

### ISSUE THREAD

**Issue by xliang-lifesize** [dlstreamer/dlstreamer#368]
Trying the dlstreamer, but failed here:

========== Converting efficientnet-b0 to IR (FP16)
Conversion command: /usr/bin/python3 -- /home/lifesize/.local/bin/mo --framework=tf --output_dir=/tmp/tmppgdkg6_g --model_name=efficientnet-b0 --input=0:sub --output=logits --input_meta_graph=/home/lifesize/intel/dl_streamer/models/public/efficientnet-b0/efficientnet-b0/model.ckpt.meta --reverse_input_channels '--layout=0:sub(NHWC)' '--input_shape=[1, 224, 224, 3]' --compress_to_fp16=True

[ ERROR ]  No node with name logits
FAILED:
efficientnet-b0

**Comment by akwrobel** [comment]
Hi @xliang-lifesize can you please share more about your setup, and how you are running the download_models.sh?

We are unable to reproduce this using the script in any scenario

**Comment by pk1d3v** [comment]
Hello!

I can't reproduce the problem when running `download_models.sh` inside Docker container `intel/dlstreamer:2022.3.0-ubuntu22-gpu555-devel`. So probably, smth is wrong in your environment. Could you try using Docker container?

```
$/opt/intel/dlstreamer/samples# ./download_models.sh 
Downloading models to folder /home/dlstreamer/intel/dl_streamer/models
################|| Downloading efficientnet-b0 ||################

========== Downloading /home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/efficientnet-b0.tar.gz
... 100%, 46280 KB, 19874 KB/s, 2 seconds passed

========== Unpacking /home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/efficientnet-b0.tar.gz

========== Converting efficientnet-b0 to IR (FP16)
Conversion command: /usr/bin/python3 -- /usr/local/bin/mo --framework=tf --data_type=FP16 --output_dir=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP16 --model_name=efficientnet-b0 --input=0:sub --output=logits --input_meta_graph=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/efficientnet-b0/model.ckpt.meta --reverse_input_channels '--layout=0:sub(NHWC)' '--input_shape=[1, 224, 224, 3]'

[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal. 
Check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html?cid=other&source=prod&campid=ww_2023_bu_IOTG_OpenVINO-2022-3&content=upg_all&medium=organic or on https://github.com/openvinotoolkit/openvino
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP16/efficientnet-b0.xml
[ SUCCESS ] BIN file: /home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP16/efficientnet-b0.bin

========== Converting efficientnet-b0 to IR (FP32)
Conversion command: /usr/bin/python3 -- /usr/local/bin/mo --framework=tf --data_type=FP32 --output_dir=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP32 --model_name=efficientnet-b0 --input=0:sub --output=logits --input_meta_graph=/home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/efficientnet-b0/model.ckpt.meta --reverse_input_channels '--layout=0:sub(NHWC)' '--input_shape=[1, 224, 224, 3]' '--layout=0:sub(NHWC)' '--input_shape=[1, 224, 224, 3]'

[ WARNING ]  Use of deprecated cli option --data_type detected. Option use in the following releases will be fatal. 
Check for a new version of Intel(R) Distribution of OpenVINO(TM) toolkit here https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html?cid=other&source=prod&campid=ww_2023_bu_IOTG_OpenVINO-2022-3&content=upg_all&medium=organic or on https://github.com/openvinotoolkit/openvino
[ INFO ] The model was converted to IR v11, the latest model format that corresponds to the source DL framework input/output format. While IR v11 is backwards compatible with OpenVINO Inference Engine API v1.0, please use API v2.0 (as of 2022.1) to take advantage of the latest improvements in IR v11.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai/latest/openvino_2_0_transition_guide.html
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP32/efficientnet-b0.xml
[ SUCCESS ] BIN file: /home/dlstreamer/intel/dl_streamer/models/public/efficientnet-b0/FP32/efficientnet-b0.bin
```

**Comment by xliang-lifesize** [comment]
The docker image works. 
I run into this issue as follow the instruction to install dlstreamer in Ubuntu 22.04.

**Comment by Arna-Maity** [comment]
Facing a similar issue:

```
========== Converting efficientnet-b0 to IR (FP16)
Conversion command: /usr/bin/python3 -- /home/shyamal/.local/bin/mo --framework=tf --output_dir=/tmp/tmp9duca3mp --model_name=efficientnet-b0 --input=0:sub --output=logits --input_meta_graph=/home/shyamal/intel/dl_streamer/models/public/efficientnet-b0/efficientnet-b0/model.ckpt.meta --reverse_input_channels '--layout=0:sub(NHWC)' '--input_shape=[1, 224, 224, 3]' --compress_to_fp16=True

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  No module named 'tensorflow'
[ ERROR ]  Traceback (most recent call last):
  File "/home/shyamal/.local/lib/python3.10/site-packages/openvino/tools/mo/front/tf/loader.py", line 18, in <module>
    import tensorflow.compat.v1 as tf_v1
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shyamal/.local/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py", line 915, in _convert
    ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
  File "/home/shyamal/.local/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py", line 591, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/home/shyamal/.local/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py", line 389, in prepare_ir
    from openvino.tools.mo.front.tf.loader import convert_to_pb
  File "/home/shyamal/.local/lib/python3.10/site-packages/openvino/tools/mo/front/tf/loader.py", line 22, in <module>
    import tensorflow as tf_v1
ModuleNotFoundError: No module named 'tensorflow'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
[ INFO ] You can also try to use legacy TensorFlow Frontend by using argument --use_legacy_frontend.

FAILED:
 
```

Using a fresh install of **Ubuntu 22.04 LTS** with just the gstreamer libraries installed from beforehand.

Test System:
*Intel NUC12WSHi5 (Core i5 1240p)*
*32 GB RAM*

Do we need to install tensorflow from beforehand prior to running this command? The documentation does not mention anything about this.

**Comment by akwrobel** [comment]
@Arna-Maity it appears you do not have Tensorflow installed which is the issue

@xliang-lifesize Can you share more information about your setup, including what DL Streamer and OpenVINO versions you are using, if you are getting them from GitHub directly, and if you have any restrictive proxy settings?
