### ISSUE TITLE
incompatible function arguments during model conversion

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [dlstreamer/dlstreamer#384]
**OS:** Ubuntu 22.04.3 LTS
**CPU:** Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz

Hello,

I installed `dlstreamer` via building from source. then ran the `download_models.sh` script and after downloading, it failed during model conversion, Find the command below and its output below.

`/usr/bin/python3 -- /usr/local/bin/mo --framework=onnx --output_dir=/usr/local/samples/models/public/aclnet/FP16 --model_name=aclnet --input=input --output=output --input_model=/usr/local/samples/models/public/aclnet/aclnet_des_53.onnx '--layout=input(NCWL)' '--input_shape=[1, 1, 1, 16000]' --compress_to_fp16=True`

```
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  load(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

Invoked with: <FrontEnd 'onnx'>, '/usr/local/samples/models/public/aclnet/aclnet_des_53.onnx', False
[ ERROR ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openvino/tools/mo/convert_impl.py", line 897, in _convert
    ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
  File "/usr/local/lib/python3.10/dist-packages/openvino/tools/mo/convert_impl.py", line 560, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/usr/local/lib/python3.10/dist-packages/openvino/tools/mo/convert_impl.py", line 414, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/usr/local/lib/python3.10/dist-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 56, in moc_pipeline
    input_model = moc_front_end.load(argv.input_model, share_weights)
TypeError: load(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

Invoked with: <FrontEnd 'onnx'>, '/usr/local/samples/models/public/aclnet/aclnet_des_53.onnx', False

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```

For reference output of `pip list`
```
Package             Version
------------------- -------------
addict              2.4.0
blinker             1.4
certifi             2023.7.22
charset-normalizer  3.3.1
cryptography        3.4.8
dbus-python         1.2.18
deep-sort-realtime  1.3.2
defusedxml          0.7.1
distro              1.7.0
distro-info         1.1+ubuntu0.1
fastjsonschema      2.17.1
filelock            3.13.1
fsspec              2023.10.0
httplib2            0.20.2
idna                3.4
importlib-metadata  4.6.4
jeepney             0.7.1
Jinja2              3.1.2
jstyleson           0.0.2
keyring             23.5.0
launchpadlib        1.10.16
lazr.restfulclient  0.14.4
lazr.uri            1.0.6
MarkupSafe          2.1.3
more-itertools      8.10.0
mpmath              1.3.0
networkx            3.1
numpy               1.25.2
oauthlib            3.2.0
onnx                1.13.1
opencv-python       4.8.1.78
openvino            2023.1.0
openvino-dev        2023.1.0
openvino-telemetry  2023.2.1
packaging           23.2
Pillow              10.1.0
pip                 23.3.1
protobuf            3.20.3
PyGObject           3.42.1
PyJWT               2.3.0
pyparsing           2.4.7
python-apt          2.4.0+ubuntu2
PyYAML              6.0.1
requests            2.31.0
scikit-build        0.17.6
scipy               1.10.1
SecretStorage       3.3.1
setuptools          59.6.0
six                 1.16.0
sympy               1.12
texttable           1.7.0
tomli               2.0.1
torch               2.1.0+cpu
torchvision         0.16.0+cpu
tqdm                4.66.1
typing_extensions   4.8.0
unattended-upgrades 0.1
urllib3             2.0.7
wadllib             1.3.6
wheel               0.37.1
zipp                1.0.0
```
Best regards,
Thanks in advance.

**Comment by akwrobel** [comment]
@eslam-ahmed-khair Can you provide more information on your setup.  It appears that you are using different versions then the release image i.e. the latest release supports OC 2023.0, and your install shows a list including a few versions of OV
openvino            2023.1.0
openvino-dev        2023.1.0
openvino-telemetry  2023.2.1

Can you please use the targeted release versions, and see if this issue still occurs.

**Comment by eslam-ahmed-khair** [comment]
@akwrobel Thank you for your response. Updating the python package versions to stated versions solved my issue.
```
openvino            2023.0.2
openvino-dev        2023.0.2
openvino-telemetry  2023.0.0
```
